extend-exclude = [".venv"]
line-length = 80
target-version = "py313"
indent-width = 4

[lint]
extend-select = ["I"]

[lint.isort]
force-single-line = true

[format]
quote-style = "double"
indent-style = "space"
