"""add product_discount and product_group tables

Revision ID: 45a928d57037
Revises: f687340c28fa
Create Date: 2025-12-04 22:44:58.291871

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45a928d57037"
down_revision: Union[str, None] = "f687340c28fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_group_id"), "product_group", ["id"], unique=True
    )
    op.create_table(
        "product_discount",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("percent", sa.Integer(), nullable=False),
        sa.Column("start_at", sa.Date(), nullable=False),
        sa.Column("end_at", sa.Date(), nullable=False),
        sa.Column("product_group_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "percent >= 1 AND percent <= 99", name="check_percent_range"
        ),
        sa.ForeignKeyConstraint(
            ["product_group_id"],
            ["product_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_discount_id"), "product_discount", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_product_discount_product_group_id"),
        "product_discount",
        ["product_group_id"],
        unique=False,
    )
    op.add_column(
        "product", sa.Column("product_group_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_product_product_group_id"),
        "product",
        ["product_group_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "product", "product_group", ["product_group_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product", type_="foreignkey")
    op.drop_index(op.f("ix_product_product_group_id"), table_name="product")
    op.drop_column("product", "product_group_id")
    op.drop_index(
        op.f("ix_product_discount_product_group_id"),
        table_name="product_discount",
    )
    op.drop_index(op.f("ix_product_discount_id"), table_name="product_discount")
    op.drop_table("product_discount")
    op.drop_index(op.f("ix_product_group_id"), table_name="product_group")
    op.drop_table("product_group")
    # ### end Alembic commands ###
