"""implement auth sessions

Revision ID: 4feef4c7061e
Revises: 97b4d294a686
Create Date: 2025-12-10 22:30:12.019256

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4feef4c7061e"
down_revision: Union[str, None] = "97b4d294a686"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_session",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("otp_code", sa.String(length=4), nullable=False),
        sa.Column("session_token", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_session_id"), "auth_session", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_auth_session_phone"), "auth_session", ["phone"], unique=False
    )
    op.create_index(
        op.f("ix_auth_session_session_token"),
        "auth_session",
        ["session_token"],
        unique=True,
    )
    op.create_index(
        op.f("ix_auth_session_user_id"),
        "auth_session",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "user", "first_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "user",
        "second_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(length=200),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "hashed_password",
        existing_type=sa.VARCHAR(length=200),
        nullable=False,
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "user", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "user",
        "second_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "user",
        "first_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_index(op.f("ix_auth_session_user_id"), table_name="auth_session")
    op.drop_index(
        op.f("ix_auth_session_session_token"), table_name="auth_session"
    )
    op.drop_index(op.f("ix_auth_session_phone"), table_name="auth_session")
    op.drop_index(op.f("ix_auth_session_id"), table_name="auth_session")
    op.drop_table("auth_session")
    # ### end Alembic commands ###
