"""create payment_option table

Revision ID: 5cde7abed854
Revises: 812cc6120ddf
Create Date: 2025-03-26 22:15:28.444129

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5cde7abed854"
down_revision: Union[str, None] = "812cc6120ddf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_option",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "company_id", "type", name="ix_company_id_payment_option_type"
        ),
    )
    op.create_index(
        op.f("ix_payment_option_company_id"),
        "payment_option",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_payment_option_id"), "payment_option", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_option_id"), table_name="payment_option")
    op.drop_index(
        op.f("ix_payment_option_company_id"), table_name="payment_option"
    )
    op.drop_table("payment_option")
    # ### end Alembic commands ###
