"""implement DeliveryInfo

Revision ID: 7565a4f1bfb5
Revises: e348340727b4
Create Date: 2025-12-14 15:18:00.557847

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7565a4f1bfb5"
down_revision: Union[str, None] = "e348340727b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("declaration_id", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("warehouse", sa.String(length=100), nullable=True),
        sa.Column(
            "full_delivery_address", sa.String(length=500), nullable=True
        ),
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("date_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_info_id"), "delivery_info", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_delivery_info_order_id"),
        "delivery_info",
        ["order_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_delivery_info_order_id"), table_name="delivery_info")
    op.drop_index(op.f("ix_delivery_info_id"), table_name="delivery_info")
    op.drop_table("delivery_info")
    # ### end Alembic commands ###
