"""add category.alias field

Revision ID: 97b4d294a686
Revises: 45a928d57037
Create Date: 2025-12-08 22:59:55.432569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b4d294a686'
down_revision: Union[str, None] = '45a928d57037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('alias', sa.String(length=120), nullable=False))
    op.create_index(op.f('ix_category_alias'), 'category', ['alias'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_alias'), table_name='category')
    op.drop_column('category', 'alias')
    # ### end Alembic commands ###
