"""add status and timestamp for order

Revision ID: d0244f79efd4
Revises: 7565a4f1bfb5
Create Date: 2025-12-14 15:27:47.053439

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0244f79efd4"
down_revision: Union[str, None] = "7565a4f1bfb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order", sa.Column("status", sa.String(length=50), nullable=False)
    )
    op.add_column("order", sa.Column("comment", sa.Text(), nullable=True))
    op.add_column(
        "order",
        sa.Column(
            "date_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "order",
        sa.Column("date_updated", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "date_updated")
    op.drop_column("order", "date_created")
    op.drop_column("order", "comment")
    op.drop_column("order", "status")
    # ### end Alembic commands ###
