"""create delivery_option table

Revision ID: e9152832dec3
Revises: 5cde7abed854
Create Date: 2025-03-26 22:18:56.226225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9152832dec3'
down_revision: Union[str, None] = '5cde7abed854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'type', name='ix_company_id_delivery_option_type')
    )
    op.create_index(op.f('ix_delivery_option_company_id'), 'delivery_option', ['company_id'], unique=False)
    op.create_index(op.f('ix_delivery_option_id'), 'delivery_option', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_option_id'), table_name='delivery_option')
    op.drop_index(op.f('ix_delivery_option_company_id'), table_name='delivery_option')
    op.drop_table('delivery_option')
    # ### end Alembic commands ###
