"""create order table

Revision ID: f687340c28fa
Revises: e9152832dec3
Create Date: 2025-03-26 22:26:14.052675

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f687340c28fa"
down_revision: Union[str, None] = "e9152832dec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("from_company_id", sa.Integer(), nullable=False),
        sa.Column("from_first_name", sa.String(length=50), nullable=False),
        sa.Column("from_second_name", sa.String(length=50), nullable=False),
        sa.Column("from_last_name", sa.String(length=50), nullable=False),
        sa.Column("from_email", sa.String(length=120), nullable=False),
        sa.Column("from_phone", sa.String(length=20), nullable=False),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("payment_option_id", sa.Integer(), nullable=False),
        sa.Column("delivery_option_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_option_id"],
            ["delivery_option.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_company_id"],
            ["company.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_option_id"],
            ["payment_option.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_cart_id"), "order", ["cart_id"], unique=False
    )
    op.create_index(
        op.f("ix_order_from_company_id"),
        "order",
        ["from_company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_from_user_id"), "order", ["from_user_id"], unique=False
    )
    op.create_index(op.f("ix_order_id"), "order", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_id"), table_name="order")
    op.drop_index(op.f("ix_order_from_user_id"), table_name="order")
    op.drop_index(op.f("ix_order_from_company_id"), table_name="order")
    op.drop_index(op.f("ix_order_cart_id"), table_name="order")
    op.drop_table("order")
    # ### end Alembic commands ###
